# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: PR Build
on:
  push:
    branches: [ terraform ]

permissions:
  id-token: write
  contents: read

jobs:
  adot-testbed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.INTEG_TEST_TFW_ROLE_ARN }}
          role-duration-seconds: 1200
          aws-region: us-west-2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: adot-testbed gradle wrapper
        working-directory: adot-testbed/
        run: gradle wrapper
      - name: adot-testbed build
        working-directory: adot-testbed/
        run: gradle build
      - name: adot-testbed test
        working-directory: adot-testbed/
        run: ./gradlew test --tests LogsTests --rerun-tasks --info